kubeoptix-harvester:
  deploy:
    enabled: true
  namespace:
    create: true
    name: shiftwise-ai
  serviceAccount:
    create: true
    name: kubeoptix-harvester
  rbac:
    createClusterRoleBinding: true
  build:
    enabled: true
    sourceSecret:
      create: false
      name: github-auth
      username: x-access-token
      token: ""

kubeoptix-analyzer:
  deploy:
    enabled: true
  namespace:
    create: false
    name: shiftwise-ai
  serviceAccount:
    create: false
    name: shiftwisea-ai-user
  rbac:
    createClusterRoleBinding: false
  build:
    enabled: true
    sourceSecret:
      create: false
      name: github-auth
      username: ""
      token: ""
