{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubeoptix-analyzer.namespace" . }}
  labels:
    {{- include "kubeoptix-analyzer.labels" . | nindent 4 }}
{{- end }}
