{{- if and .Values.deploy.enabled .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name }}
  namespace: {{ include "kubeoptix-analyzer.namespace" . }}
  labels:
    {{- include "kubeoptix-analyzer.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kubeoptix-analyzer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.headless.port }}
      targetPort: {{ .Values.service.headless.port }}
      protocol: TCP
{{- end }}
