apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: shiftwise-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: default-route-openshift-image-registry.apps-crc.testing/shiftwise-ai/shiftwise-operator-catalog:v1.0.0
  displayName: ShiftWise Operator Catalog
  publisher: ShiftWise AI
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 10m
