apiVersion: v1
kind: ServiceAccount
metadata:
  name: shiftwise-operator-controller-manager
  namespace: shiftwise-ai
  labels:
    app.kubernetes.io/name: shiftwise-operator
    app.kubernetes.io/part-of: kubeoptix
