apiVersion: shiftwise.ai/v1alpha1
kind: ShiftWise
metadata:
  name: shiftwise
  namespace: shiftwise-ai
spec:
  storage:
    name: harvester-app-data
    size: 10Gi
    accessModes:
      - ReadWriteOnce
