//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a copy of ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ComponentsSpec) DeepCopyInto(out *ComponentsSpec) {
	*out = *in
	in.Harvester.DeepCopyInto(&out.Harvester)
	in.Analyzer.DeepCopyInto(&out.Analyzer)
	in.CoreAI.DeepCopyInto(&out.CoreAI)
	in.Configurations.DeepCopyInto(&out.Configurations)
	in.Reporter.DeepCopyInto(&out.Reporter)
	in.Dashboard.DeepCopyInto(&out.Dashboard)
}

// DeepCopy returns a copy of ComponentsSpec.
func (in *ComponentsSpec) DeepCopy() *ComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *CredentialsSpec) DeepCopyInto(out *CredentialsSpec) {
	*out = *in
}

// DeepCopy returns a copy of CredentialsSpec.
func (in *CredentialsSpec) DeepCopy() *CredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ImagesSpec) DeepCopyInto(out *ImagesSpec) {
	*out = *in
}

// DeepCopy returns a copy of ImagesSpec.
func (in *ImagesSpec) DeepCopy() *ImagesSpec {
	if in == nil {
		return nil
	}
	out := new(ImagesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWise) DeepCopyInto(out *ShiftWise) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a copy of ShiftWise.
func (in *ShiftWise) DeepCopy() *ShiftWise {
	if in == nil {
		return nil
	}
	out := new(ShiftWise)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of ShiftWise.
func (in *ShiftWise) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWiseList) DeepCopyInto(out *ShiftWiseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShiftWise, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a copy of ShiftWiseList.
func (in *ShiftWiseList) DeepCopy() *ShiftWiseList {
	if in == nil {
		return nil
	}
	out := new(ShiftWiseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of ShiftWiseList.
func (in *ShiftWiseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWiseSpec) DeepCopyInto(out *ShiftWiseSpec) {
	*out = *in
	out.Images = in.Images
	in.Storage.DeepCopyInto(&out.Storage)
	out.Credentials = in.Credentials
	out.GitSource = in.GitSource
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy returns a copy of ShiftWiseSpec.
func (in *ShiftWiseSpec) DeepCopy() *ShiftWiseSpec {
	if in == nil {
		return nil
	}
	out := new(ShiftWiseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWiseStatus) DeepCopyInto(out *ShiftWiseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a copy of ShiftWiseStatus.
func (in *ShiftWiseStatus) DeepCopy() *ShiftWiseStatus {
	if in == nil {
		return nil
	}
	out := new(ShiftWiseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GitSourceSpec) DeepCopyInto(out *GitSourceSpec) {
	*out = *in
}

func (in *GitSourceSpec) DeepCopy() *GitSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GitSourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a copy of StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
