//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ShiftWise) DeepCopyInto(out *ShiftWise) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a copy of ShiftWise.
func (in *ShiftWise) DeepCopy() *ShiftWise {
	if in == nil {
		return nil
	}
	out := new(ShiftWise)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of ShiftWise.
func (in *ShiftWise) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWiseList) DeepCopyInto(out *ShiftWiseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShiftWise, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a copy of ShiftWiseList.
func (in *ShiftWiseList) DeepCopy() *ShiftWiseList {
	if in == nil {
		return nil
	}
	out := new(ShiftWiseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of ShiftWiseList.
func (in *ShiftWiseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWiseSpec) DeepCopyInto(out *ShiftWiseSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy returns a copy of ShiftWiseSpec.
func (in *ShiftWiseSpec) DeepCopy() *ShiftWiseSpec {
	if in == nil {
		return nil
	}
	out := new(ShiftWiseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ShiftWiseStatus) DeepCopyInto(out *ShiftWiseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a copy of ShiftWiseStatus.
func (in *ShiftWiseStatus) DeepCopy() *ShiftWiseStatus {
	if in == nil {
		return nil
	}
	out := new(ShiftWiseStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a copy of StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
