{{- if .Values.build.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "kubeoptix-harvester.fullname" . }}
  namespace: {{ include "kubeoptix-harvester.namespace" . }}
  labels:
    {{- include "kubeoptix-harvester.labels" . | nindent 4 }}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.build.source.gitUri | quote }}
      ref: {{ .Values.build.source.gitRef | quote }}
    {{- if .Values.build.source.contextDir }}
    contextDir: {{ .Values.build.source.contextDir | quote }}
    {{- end }}
    {{- $sourceSecretName := .Values.build.sourceSecret.name | default (printf "%s-git-auth" (include "kubeoptix-harvester.fullname" .)) }}
    {{- if or .Values.build.sourceSecret.create .Values.build.sourceSecret.name }}
    sourceSecret:
      name: {{ $sourceSecretName }}
    {{- end }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.containerfilePath | quote }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ printf "%s:%s" .Values.build.imageStreamName .Values.build.outputTag | quote }}
{{- end }}
