{{- if .Values.build.sourceSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.build.sourceSecret.name | default (printf "%s-git-auth" (include "kubeoptix-harvester.fullname" .)) }}
  namespace: {{ include "kubeoptix-harvester.namespace" . }}
  labels:
    {{- include "kubeoptix-harvester.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.build.sourceSecret.username | default "x-access-token" | quote }}
  password: {{ .Values.build.sourceSecret.token | quote }}
{{- end }}
