{{- if and .Values.deploy.enabled .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ include "kubeoptix-harvester.namespace" . }}
  labels:
    {{- include "kubeoptix-harvester.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.service.api.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
{{- end }}
