{{- if and .Values.deploy.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeoptix-harvester.serviceAccountName" . }}
  namespace: {{ include "kubeoptix-harvester.namespace" . }}
  labels:
    {{- include "kubeoptix-harvester.labels" . | nindent 4 }}
{{- end }}
