{{- if and .Values.deploy.enabled .Values.service.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name }}
  namespace: {{ include "kubeoptix-harvester.namespace" . }}
  labels:
    {{- include "kubeoptix-harvester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    {{- include "kubeoptix-harvester.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
{{- end }}
