apiVersion: shiftwise.ai/v1alpha1
kind: ShiftWise
metadata:
  name: shiftwise
  namespace: shiftwise-ai
spec:
  targetNamespace: shiftwise-ai
  images:
    harvester: quay.io/shiftwise-ai/kubeoptix-harvester:latest
    analyzer: quay.io/shiftwise-ai/kubeoptix-analyzer:latest
    coreAi: quay.io/shiftwise-ai/kubeoptix-core-ai:latest
    configurations: quay.io/shiftwise-ai/kubeoptix-configurations:latest
    reporter: quay.io/shiftwise-ai/kubeoptix-reporter:latest
    dashboard: quay.io/shiftwise-ai/kubeoptix-dashboard:latest
    postgres: registry.redhat.io/rhel9/postgresql-16:latest
  storage:
    size: 10Gi
  credentials:
    existingSecret: kubeoptix-credentials
  components:
    harvester:
      enabled: true
    analyzer:
      enabled: true
    coreAi:
      enabled: true
    configurations:
      enabled: true
    reporter:
      enabled: true
    dashboard:
      enabled: true
