apiVersion: shiftwise.ai/v1alpha1
kind: ShiftWise
metadata:
  name: shiftwise
  namespace: shiftwise-ai
spec:
  targetNamespace: shiftwise-ai
  images:
    harvester: quay.io/parraes/kubeoptix-harvester:v0.1.0
    analyzer: quay.io/parraes/kubeoptix-analyzer:v0.1.0
    coreAi: quay.io/parraes/kubeoptix-core-ai:v0.1.0
    configurations: quay.io/parraes/kubeoptix-configurations:v0.1.0
    reporter: quay.io/parraes/kubeoptix-reporter:v0.1.0
    dashboard: quay.io/parraes/kubeoptix-dashboard:v0.1.0
    postgres: registry.redhat.io/rhel9/postgresql-16:latest
  storage:
    size: 10Gi
  credentials:
    existingSecret: kubeoptix-credentials
  components:
    harvester:
      enabled: true
    analyzer:
      enabled: true
    coreAi:
      enabled: true
    configurations:
      enabled: true
    reporter:
      enabled: true
    dashboard:
      enabled: true
